site_name: Holistic Pwning
site_description: 'Bring you offensive spirit to the next level'
site_url: https://s-lck.github.io/HolisticPwning

repo_url: https://github.com/s-lck/HolisticPwning
edit_uri: blob/main/docs/

theme:
  name: material
  custom_dir: overrides
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github
  palette:
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: brown
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default      
      primary: brown    
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.tooltips
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest

extra_css:
    - custom.css

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized
  - social
